#!/bin/bash
fichier=$(cat certificat.cfg)
    fichier=$(echo $fichier | tr ' ' '=');
    countryName=$(echo $fichier | awk -F '=' '{print $2}')
    stateOrProvinceName=$(echo $fichier | awk -F '=' '{print $4}')
    localityName=$(echo $fichier | awk -F '=' '{print $6}')
    organizationName=$(echo $fichier | awk -F '=' '{print $7}')
    organizationUnitName=$(echo $fichier | awk -F '=' '{print $8}')
    commonName=$(echo $fichier | awk -F '=' '{print $10}')
    email=$(echo $fichier | awk -F '=' '{print $12}')


 echo $countryName
    echo "State or province name = "$stateOrProvinceName
    echo "Locality name = "$localityName
    echo "Organization name = "$organizationName
    echo "Organizational Unit Name = "$organizationUnitName
    echo "Common name = "$commonName
    echo "Email Address = "$email